config {
    type: "table",
    name: "crime_count",
    description: "Stores the count of each type of crime committed in each district",
    tags: ["eda"],
        columns: {
        primary_type: "Type of offence committed",
        district: "District in which the crime took place.",
        cases_count: "Count of cases"
    }
}

SELECT
  primary_type,
  district,
  COUNT(*) AS cases_count
FROM
  ${ref("crime")}
  GROUP BY district, primary_type ORDER BY primary_type
